apiVersion: apps/v1
kind: Deployment
metadata:
  name: valentine-app
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: valentine-app
  template:
    metadata:
      name: valentine-app
      labels:
        app: valentine-app
    spec:
      containers:
        - name: valentine
          image: ari786/valentine-html:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: valentine-svc
  namespace: webapps
spec:
  type: NodePort
  selector:
    app: valentine-app
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
    